<a href="https://colab.research.google.com/github/EthanFerba/IDX-Exchange-Data-Science/blob/main/Data_Cleaning_and_Analysis_Phase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

For this phase, we are going to reuse the same code base that we used to create the orginal EDA. The reason for this is becuase for the EDA phase we already did some of the steps of cleaning to get the preliminary graphs.

In [447]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import plotly.express as px
plt.style.use('ggplot')
pd.set_option('display.max_columns', 200)
pd.set_option("display.float_format", lambda x: "%.2f" % x)

Just build the basic libraires that I will need to pre-process

In [448]:
df22_23 = pd.read_csv('/content/CRMLSSold20220101_20231231_filled(first 2 years).csv')
df24 = pd.read_csv('/content/CRMLSSold202401_filled(january_2024).csv')

/tmp/ipykernel_1260/819583140.py:1: DtypeWarning:

Columns (78,79) have mixed types. Specify dtype option on import or set low_memory=False.

In [449]:
mdf = pd.concat([df22_23, df24], ignore_index=True)

In [450]:
mdf.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,MlsStatus,ElementarySchool,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,BuyerAgencyCompensationType,StreetNumberNumeric,ListingId,BathroomsTotalInteger,City,BuyerAgencyCompensation,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled
0,"Carpet,Wood",True,NaN,NaN,True,98000.00,556366533,michellefsellsoc@gmail.com,2022-02-25,95000.00,Michelle,Fairchild,33.70,-117.96,231 Albatross Lane,ManufacturedInPark,1368.00,98000.00,86.00,Premiere Choice R E Inc,Premiere Choice R E Inc,Premiere Choice R E Inc,Michelle Fairchild,Josh,Lukasiewicz,ocfairmic,Michelle,Fairchild,NaN,NaN,NaN,556366533.00,16 - Fountain Valley / Northeast HB,NaN,Orange,Closed,NaN,NaN,2.00,NaN,NaN,NaN,Rancho la Siesta 55+ Senior,OrangeCounty,1969.00,Item,231.00,OC21227682,2.00,Fountain Valley,1500.00,NaN,NaN,2.00,2022-02-25,NaN,NaN,2022-01-28,2021-10-13,NaN,NaN,CA,NaN,NaN,NaN,1.00,NaN,One,NaN,NaN,NaN,NaN,0.00,ABC Unified,92708,0.00,NaN,NaN,False,False
1,NaN,False,NaN,NaN,False,1200.00,556366530,dineshcalre@gmail.com,2022-02-19,1200.00,DINESH,MAYANI,34.50,-117.19,21601 Powhatan Road 2,ResidentialLease,850.00,1200.00,125.00,California Real Estate & Investments,California Real Estate & Investments,NaN,DINESH MAYANI,NaN,NaN,evmayadin,DINESH,MAYANI,NaN,NaN,NaN,556366530.00,APPV - Apple Valley,NaN,San Bernardino,Closed,NaN,False,1.00,NaN,Apartment,0.99,NaN,EastValley,1987.00,Item,21601.00,EV21227683,1.00,Apple Valley,100.00,NaN,NaN,2.00,2022-02-19,NaN,NaN,2022-02-19,2021-10-13,NaN,NaN,CA,NaN,NaN,False,1.00,NaN,One,NaN,43000.00,2.00,False,1.00,Apple Valley Unified,92308,0.00,43000.00,NaN,False,False
2,NaN,True,NaN,NaN,False,1100000.00,556366044,cindydavishomes@gmail.com,2022-04-15,1100000.00,Cindy,Davis,32.98,-117.26,827 Del Mar Downs Rd. D,Residential,1344.00,1100000.00,106.00,SD Home Source Realty,Compass,NaN,Cindy Davis,NaN,NaN,SAND-646850,Lindsay,Dunlap,NaN,Monthly,NaN,556366044.00,92075 - Solana Beach,NaN,San Diego,Closed,NaN,True,2.00,NaN,Townhouse,NaN,NaN,SanDiego,1974.00,Item1,827.00,NDP2111697,3.00,Solana Beach,1.50,NaN,NaN,3.00,2022-04-15,NaN,NaN,2022-02-03,2021-10-13,NaN,NaN,CA,NaN,NaN,True,2.00,NaN,Two,NaN,NaN,0.00,NaN,1.00,Solana Beach,92075,370.00,NaN,NaN,False,False
3,NaN,True,NaN,NaN,False,2499999.00,556365765,bryanmeathe@gmail.com,2022-01-04,2499999.00,Bryan,Meathe,33.15,-117.34,295 Chinquapin Ave,Residential,2645.00,2499999.00,37.00,Coldwell Banker Realty,ERA Ranch & Sea Realty,NaN,Bryan Meathe,NaN,NaN,101046,Bill,Kellaway,NaN,Monthly,NaN,556365765.00,92008 - Carlsbad,NaN,San Diego,Closed,NaN,True,2.00,NaN,SingleFamilyResidence,0.31,NaN,NorthSanDiegoCounty,2016.00,Item1,295.00,NDP2111696,4.00,Carlsbad,2.25,NaN,NaN,4.00,2022-01-04,NaN,NaN,2021-11-19,2021-10-13,NaN,NaN,CA,NaN,NaN,False,NaN,NaN,ThreeOrMore,NaN,13376.00,0.00,NaN,2.00,Carlsbad Unified,92008,140.00,13376.00,NaN,False,False
4,"Carpet,Tile",NaN,NaN,NaN,NaN,598888.00,556365290,steven@westsideres.com,2022-01-12,640000.00,Steven,Larson,37.30,-121.84,NaN,Residential,1198.00,598888.00,15.00,Westside Real Estate Services,Portico Realty and Investment,NaN,Steven Larson,NaN,NaN,ML477710,Tammy,Nguyen,NaN,Monthly,NaN,556365290.00,699 - Not Defined,NaN,Santa Clara,Closed,NaN,True,2.00,NaN,Townhouse,0.06,NaN,MLSListings,1989.00,Item1,NaN,ML81866683,3.00,San Jose,2.50,NaN,NaN,2.00,2022-01-12,NaN,NaN,2021-12-17,2021-10-13,NaN,NaN,CA,NaN,NaN,True,NaN,NaN,NaN,NaN,2738.00,NaN,False,1.00,Other,95111,300.00,2738.00,NaN,False,False

Next we would want to load in the data that we are going to use. during this step I went and merged the two data sets together. I did this because one sources covers the full years of 2022 and 2023 and the other one covers january 2024. I think in total it would give a great general outlook of the potenital fluxuation of the DV overtime and through different seasons.

In [451]:
mdf.shape

(175786, 80)

In [452]:
mdf.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,ListingKeyNumeric,TaxAnnualAmount,ParkingTotal,LotSizeAcres,YearBuilt,StreetNumberNumeric,BathroomsTotalInteger,BuyerAgencyCompensation,TaxYear,BuildingAreaTotal,BedroomsTotal,ElementarySchoolDistrict,BelowGradeFinishedArea,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict
count,175216.00,175786.00,175784.00,175449.00,175452.00,161204.00,175503.00,175785.00,0.00,0.00,175785.00,805.00,157934.00,158060.00,166540.00,174663.00,165403.00,175673.00,123.00,21278.00,161814.00,0.00,569.00,0.00,129872.00,158864.00,89258.00,151855.00,118595.00,158599.00,0.00
mean,863526.52,1001541747.42,797526.27,34.65,-118.59,13093.57,796478.57,39.88,NaN,NaN,1001541552.79,1254131.87,18.19,74.85,1977.22,23394.58,2.41,159.45,1939.20,2696.09,3.06,NaN,9891557.08,NaN,1.37,56738.45,1.93,1.79,167.04,693961.99,NaN
std,5877599.67,139131698.08,1683585.21,2.15,2.82,3202100.28,1389326.31,94.63,NaN,NaN,139132069.90,35244961.84,3503.05,7250.48,26.57,2196919.28,1.23,1910.05,396.69,8951.96,1.24,NaN,235945692.05,NaN,0.48,2488800.59,1.68,5.09,1227.55,97793293.14,NaN
min,0.00,421448934.00,0.00,-117.45,-156.45,0.00,0.00,-129.00,NaN,NaN,421448934.00,0.00,-46.00,0.00,1776.00,0.00,0.00,0.00,20.00,0.00,0.00,NaN,0.00,NaN,1.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,44522.50,1037835423.25,35437.50,33.74,-118.76,1176.00,42000.00,7.00,NaN,NaN,1037835424.00,170.00,2.00,0.12,1959.00,790.00,2.00,2.00,2020.00,1176.00,2.00,NaN,0.00,NaN,1.00,4815.00,1.00,1.00,0.00,5100.00,NaN
50%,599000.00,1040602172.50,600000.00,34.05,-118.08,1568.00,599000.00,16.00,NaN,NaN,1040602173.00,4592.00,2.00,0.17,1978.00,2751.00,2.00,2.50,2022.00,1690.00,3.00,NaN,0.00,NaN,1.00,7000.00,2.00,2.00,0.00,7234.00,NaN
75%,995000.00,1045566501.50,1000000.00,34.51,-117.34,2128.00,995000.00,41.00,NaN,NaN,1045566502.00,15400.00,2.50,0.29,1998.00,10721.00,3.00,2.50,2022.00,2616.00,4.00,NaN,0.00,NaN,2.00,11326.00,3.00,2.00,270.00,12697.00,NaN
max,965000000.00,1067652762.00,417255000.00,564.00,151.08,909099090.00,245000000.00,4250.00,NaN,NaN,1067652762.00,999999999.00,808885.00,1867743.00,2024.00,650191015.00,44.00,100000.00,2023.00,651289.00,56.00,NaN,5628182881.00,NaN,2.00,449277840.00,255.00,600.00,404000.00,36677520892.00,NaN

In [453]:
mdf.columns

Index(['Flooring', 'ViewYN', 'WaterfrontYN', 'BasementYN', 'PoolPrivateYN',
       'OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'MlsStatus', 'ElementarySchool',
       'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType',
       'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'ListingId',
       'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'latfilled', 'lonfilled'],
      dtype='object')

After taking a look at the orginal columns, there are a lot that might not add a lot of value into analysis which means we can exclude them. (I think towards the end we can look back at these different feilds and add them back in just to see if there is any meaningful effect or not to the DV).

Thinks like Flooring and ListAgentEmail can be excluded. I think there might be a potential to look at the indivdual agent to see if they have an effect, but again that can come in handy later.

In [454]:
reducedmdf = mdf[[
       'ClosePrice','Latitude',
       'Longitude', 'PropertyType', 'LivingArea','CloseDate',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName','ListingContractDate' , 'ListAgentFullName', 'AssociationFeeFrequency', 'CountyOrParish',
       'AttachedGarageYN', 'ParkingTotal', 'PropertySubType',
       'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt',
       'BathroomsTotalInteger', 'City',
       'BuildingAreaTotal', 'BedroomsTotal',
       'PurchaseContractDate', 'FireplaceYN', 'Stories',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict', 'Flooring', 'BasementYN']]

In [455]:
reducedmdf.head()

,ClosePrice,Latitude,Longitude,PropertyType,LivingArea,CloseDate,ListPrice,DaysOnMarket,ListOfficeName,ListingContractDate,ListAgentFullName,AssociationFeeFrequency,CountyOrParish,AttachedGarageYN,ParkingTotal,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,BathroomsTotalInteger,City,BuildingAreaTotal,BedroomsTotal,PurchaseContractDate,FireplaceYN,Stories,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,Flooring,BasementYN
0,95000.00,33.70,-117.96,ManufacturedInPark,1368.00,2022-02-25,98000.00,86.00,Premiere Choice R E Inc,2021-10-13,Michelle Fairchild,NaN,Orange,NaN,2.00,NaN,NaN,Rancho la Siesta 55+ Senior,OrangeCounty,1969.00,2.00,Fountain Valley,NaN,2.00,2022-01-28,NaN,1.00,One,NaN,NaN,NaN,NaN,0.00,ABC Unified,92708,0.00,NaN,NaN,"Carpet,Wood",NaN
1,1200.00,34.50,-117.19,ResidentialLease,850.00,2022-02-19,1200.00,125.00,California Real Estate & Investments,2021-10-13,DINESH MAYANI,NaN,San Bernardino,False,1.00,Apartment,0.99,NaN,EastValley,1987.00,1.00,Apple Valley,NaN,2.00,2022-02-19,False,1.00,One,NaN,43000.00,2.00,False,1.00,Apple Valley Unified,92308,0.00,43000.00,NaN,NaN,NaN
2,1100000.00,32.98,-117.26,Residential,1344.00,2022-04-15,1100000.00,106.00,SD Home Source Realty,2021-10-13,Cindy Davis,Monthly,San Diego,True,2.00,Townhouse,NaN,NaN,SanDiego,1974.00,3.00,Solana Beach,NaN,3.00,2022-02-03,True,2.00,Two,NaN,NaN,0.00,NaN,1.00,Solana Beach,92075,370.00,NaN,NaN,NaN,NaN
3,2499999.00,33.15,-117.34,Residential,2645.00,2022-01-04,2499999.00,37.00,Coldwell Banker Realty,2021-10-13,Bryan Meathe,Monthly,San Diego,True,2.00,SingleFamilyResidence,0.31,NaN,NorthSanDiegoCounty,2016.00,4.00,Carlsbad,NaN,4.00,2021-11-19,False,NaN,ThreeOrMore,NaN,13376.00,0.00,NaN,2.00,Carlsbad Unified,92008,140.00,13376.00,NaN,NaN,NaN
4,640000.00,37.30,-121.84,Residential,1198.00,2022-01-12,598888.00,15.00,Westside Real Estate Services,2021-10-13,Steven Larson,Monthly,Santa Clara,True,2.00,Townhouse,0.06,NaN,MLSListings,1989.00,3.00,San Jose,NaN,2.00,2021-12-17,True,NaN,NaN,NaN,2738.00,NaN,False,1.00,Other,95111,300.00,2738.00,NaN,"Carpet,Tile",NaN

In [456]:
reducedmdf.shape

(175786, 40)

In [457]:
rdf = reducedmdf[reducedmdf['PropertyType'] == 'Residential']
rdf = rdf[rdf['PropertySubType'] == 'SingleFamilyResidence']
rdf.head()

,ClosePrice,Latitude,Longitude,PropertyType,LivingArea,CloseDate,ListPrice,DaysOnMarket,ListOfficeName,ListingContractDate,ListAgentFullName,AssociationFeeFrequency,CountyOrParish,AttachedGarageYN,ParkingTotal,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,BathroomsTotalInteger,City,BuildingAreaTotal,BedroomsTotal,PurchaseContractDate,FireplaceYN,Stories,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,Flooring,BasementYN
3,2499999.00,33.15,-117.34,Residential,2645.00,2022-01-04,2499999.00,37.00,Coldwell Banker Realty,2021-10-13,Bryan Meathe,Monthly,San Diego,True,2.00,SingleFamilyResidence,0.31,NaN,NorthSanDiegoCounty,2016.00,4.00,Carlsbad,NaN,4.00,2021-11-19,False,NaN,ThreeOrMore,NaN,13376.00,0.00,NaN,2.00,Carlsbad Unified,92008,140.00,13376.00,NaN,NaN,NaN
6,640000.00,34.24,-117.20,Residential,2070.00,2022-01-10,565000.00,13.00,Label Realty Group,2021-10-12,Joseph Guzman,NaN,San Bernardino,True,1.00,SingleFamilyResidence,0.08,NaN,TriCounties,2007.00,3.00,Lake Arrowhead,NaN,3.00,2021-10-26,True,NaN,ThreeOrMore,NaN,3397.00,0.00,False,1.00,Rim of the World,92352,0.00,3397.00,NaN,NaN,NaN
7,438000.00,34.11,-117.44,Residential,1174.00,2022-03-23,349999.00,3.00,INTERNATIONAL REAL ESTATE SVCS,2021-10-13,ELIAS AGUAYO,NaN,San Bernardino,True,2.00,SingleFamilyResidence,0.23,NaN,CitrusValley,1960.00,2.00,Fontana,NaN,3.00,2021-10-16,False,1.00,One,NaN,9900.00,3.00,False,2.00,Fontana Unified,92336,0.00,9900.00,NaN,NaN,NaN
12,615000.00,33.78,-116.45,Residential,1996.00,2022-01-10,599000.00,81.00,"Whitestar Management, Inc",2021-10-13,Rhonda Belous,Monthly,Riverside,False,4.00,SingleFamilyResidence,0.14,Rio Del Sol,CaliforniaDesert,2005.00,2.00,Cathedral City,NaN,2.00,2022-01-04,True,NaN,NaN,NaN,6098.00,NaN,NaN,2.00,NaN,92234,195.00,6098.00,NaN,"Carpet,Tile",NaN
14,399990.00,39.77,-121.59,Residential,1422.00,2022-01-19,399990.00,63.00,"3Tree Realty, Inc.",2021-04-09,Allegra Gigante-Luft,NaN,Butte,True,2.00,SingleFamilyResidence,0.28,NaN,SierraNorthValley,2021.00,2.00,Paradise,NaN,3.00,2021-12-21,False,1.00,One,NaN,12197.00,3.00,True,2.00,Paradise Unified,95969,0.00,12197.00,NaN,NaN,NaN

In [458]:
rdf.shape
rdf['CloseDate'] = pd.to_datetime(rdf['CloseDate'])
rdf['ListingContractDate'] = pd.to_datetime(rdf['ListingContractDate'])

In [459]:
rdf.dtypes

ClosePrice                             float64
Latitude                               float64
Longitude                              float64
PropertyType                            object
LivingArea                             float64
CloseDate                       datetime64[ns]
ListPrice                              float64
DaysOnMarket                           float64
ListOfficeName                          object
ListingContractDate             datetime64[ns]
ListAgentFullName                       object
AssociationFeeFrequency                 object
CountyOrParish                          object
AttachedGarageYN                        object
ParkingTotal                           float64
PropertySubType                         object
LotSizeAcres                           float64
SubdivisionName                         object
BuyerOfficeAOR                          object
YearBuilt                              float64
BathroomsTotalInteger                  float64
City                                    object
BuildingAreaTotal                      float64
BedroomsTotal                          float64
PurchaseContractDate                    object
FireplaceYN                             object
Stories                                float64
Levels                                  object
LotSizeDimensions                       object
LotSizeArea                            float64
MainLevelBedrooms                      float64
NewConstructionYN                       object
GarageSpaces                           float64
HighSchoolDistrict                      object
PostalCode                              object
AssociationFee                         float64
LotSizeSquareFeet                      float64
MiddleOrJuniorSchoolDistrict           float64
Flooring                                object
BasementYN                              object
dtype: object

Removing the duplicatess

In [460]:
rdf = rdf.loc[~rdf.duplicated(subset = ['ClosePrice','CloseDate','ListAgentFullName'])] \
.reset_index(drop = True)

In [461]:
rdf

,ClosePrice,Latitude,Longitude,PropertyType,LivingArea,CloseDate,ListPrice,DaysOnMarket,ListOfficeName,ListingContractDate,ListAgentFullName,AssociationFeeFrequency,CountyOrParish,AttachedGarageYN,ParkingTotal,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,BathroomsTotalInteger,City,BuildingAreaTotal,BedroomsTotal,PurchaseContractDate,FireplaceYN,Stories,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,Flooring,BasementYN
0,2499999.00,33.15,-117.34,Residential,2645.00,2022-01-04,2499999.00,37.00,Coldwell Banker Realty,2021-10-13,Bryan Meathe,Monthly,San Diego,True,2.00,SingleFamilyResidence,0.31,NaN,NorthSanDiegoCounty,2016.00,4.00,Carlsbad,NaN,4.00,2021-11-19,False,NaN,ThreeOrMore,NaN,13376.00,0.00,NaN,2.00,Carlsbad Unified,92008,140.00,13376.00,NaN,NaN,NaN
1,640000.00,34.24,-117.20,Residential,2070.00,2022-01-10,565000.00,13.00,Label Realty Group,2021-10-12,Joseph Guzman,NaN,San Bernardino,True,1.00,SingleFamilyResidence,0.08,NaN,TriCounties,2007.00,3.00,Lake Arrowhead,NaN,3.00,2021-10-26,True,NaN,ThreeOrMore,NaN,3397.00,0.00,False,1.00,Rim of the World,92352,0.00,3397.00,NaN,NaN,NaN
2,438000.00,34.11,-117.44,Residential,1174.00,2022-03-23,349999.00,3.00,INTERNATIONAL REAL ESTATE SVCS,2021-10-13,ELIAS AGUAYO,NaN,San Bernardino,True,2.00,SingleFamilyResidence,0.23,NaN,CitrusValley,1960.00,2.00,Fontana,NaN,3.00,2021-10-16,False,1.00,One,NaN,9900.00,3.00,False,2.00,Fontana Unified,92336,0.00,9900.00,NaN,NaN,NaN
3,615000.00,33.78,-116.45,Residential,1996.00,2022-01-10,599000.00,81.00,"Whitestar Management, Inc",2021-10-13,Rhonda Belous,Monthly,Riverside,False,4.00,SingleFamilyResidence,0.14,Rio Del Sol,CaliforniaDesert,2005.00,2.00,Cathedral City,NaN,2.00,2022-01-04,True,NaN,NaN,NaN,6098.00,NaN,NaN,2.00,NaN,92234,195.00,6098.00,NaN,"Carpet,Tile",NaN
4,399990.00,39.77,-121.59,Residential,1422.00,2022-01-19,399990.00,63.00,"3Tree Realty, Inc.",2021-04-09,Allegra Gigante-Luft,NaN,Butte,True,2.00,SingleFamilyResidence,0.28,NaN,SierraNorthValley,2021.00,2.00,Paradise,NaN,3.00,2021-12-21,False,1.00,One,NaN,12197.00,3.00,True,2.00,Paradise Unified,95969,0.00,12197.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86893,1845000.00,33.47,-117.66,Residential,3480.00,2024-01-26,1990900.00,46.00,Keller Williams Realty,2022-05-18,Cesi Pagano,Monthly,Orange,True,3.00,SingleFamilyResidence,0.27,Meredith Canyon (MC),OrangeCounty,1975.00,4.00,San Juan Capistrano,NaN,5.00,2024-01-16,True,2.00,Two,NaN,11544.00,1.00,False,3.00,Capistrano Unified,92675,150.00,11544.00,NaN,"Carpet,Stone,Tile,Wood",NaN
86894,790000.00,33.97,-118.01,Residential,1380.00,2024-01-18,769000.00,0.00,First Team Real Estate,2022-05-03,Margaret Sun,NaN,Los Angeles,True,2.00,SingleFamilyResidence,0.21,NaN,TriCounties,1951.00,2.00,Whittier,NaN,3.00,2022-05-04,True,1.00,One,NaN,9136.00,3.00,False,2.00,Whittier Union High,90602,NaN,9136.00,NaN,NaN,NaN
86895,530000.00,37.74,-121.45,Residential,1461.00,2024-01-23,448888.00,26.00,Coldwell Banker Realty,2022-02-11,Daniel Moskowitz,NaN,San Joaquin,True,2.00,SingleFamilyResidence,0.09,NaN,MLSListings,1995.00,3.00,Tracy,NaN,3.00,2023-06-12,True,NaN,NaN,NaN,4125.00,NaN,False,2.00,Tracy Joint Unified,95376,NaN,4125.00,NaN,NaN,NaN
86896,480000.00,39.80,-121.71,Residential,4015.00,2024-01-05,480000.00,9.00,BPS Properties,2021-12-08,Brooke Shelton,NaN,Butte,True,4.00,SingleFamilyResidence,5.38,NaN,SierraNorthValley,1980.00,4.00,Chico,NaN,3.00,2021-12-17,True,2.00,Two,NaN,234353.00,1.00,False,4.00,Chico Unified,95928,0.00,234353.00,NaN,NaN,NaN
86897,1250000.00,33.39,-117.23,Residential,3732.00,2024-01-31,1300000.00,530.00,Mission Real Estate & Mortgage,2022-07-18,Tony Totanes,NaN,San Diego,True,7.00,SingleFamilyResidence,0.55,NaN,NorthSanDiegoCounty,1979.00,5.00,Fallbrook,NaN,7.00,2023-08-07,True,NaN,MultiSplit,NaN,23958.00,7.00,NaN,2.00,Fallbrook Union,92028,0.00,23958.00,NaN,NaN,NaN

In [462]:
rdf = rdf.dropna(subset = ['Latitude', 'LivingArea'])
rdf = rdf.dropna(subset = ['ListAgentFullName'])

In [463]:
rdf.shape

(86727, 40)

In [464]:
rdf = rdf[rdf['CloseDate'] > rdf['ListingContractDate']]

In [465]:
rdf.shape

(85923, 40)

In [466]:
rdf['AssociationFee'].std()

1696.6163628325758

In [467]:
rdf.isna().mean() * 100

ClosePrice                       0.00
Latitude                         0.00
Longitude                        0.00
PropertyType                     0.00
LivingArea                       0.00
CloseDate                        0.00
ListPrice                        0.00
DaysOnMarket                     0.00
ListOfficeName                   0.00
ListingContractDate              0.00
ListAgentFullName                0.00
AssociationFeeFrequency         76.48
CountyOrParish                   0.00
AttachedGarageYN                11.21
ParkingTotal                     8.60
PropertySubType                  0.00
LotSizeAcres                     1.73
SubdivisionName                 66.55
BuyerOfficeAOR                   4.47
YearBuilt                        0.08
BathroomsTotalInteger            0.03
City                             0.33
BuildingAreaTotal               94.53
BedroomsTotal                    0.00
PurchaseContractDate             0.01
FireplaceYN                      1.96
Stories                         17.01
Levels                          13.87
LotSizeDimensions               93.81
LotSizeArea                      1.67
MainLevelBedrooms               41.56
NewConstructionYN               19.28
GarageSpaces                     3.32
HighSchoolDistrict              24.81
PostalCode                       0.00
AssociationFee                  31.58
LotSizeSquareFeet                1.69
MiddleOrJuniorSchoolDistrict   100.00
Flooring                        36.17
BasementYN                      97.47
dtype: float64

After looking at the fields over again and seeing what might fit best for the model, I began to remove some of the fields that would cause to much problems. Some of the fields are middleorjuniorshcoold district, assocationfeefrequency, taxanualamount, subdivision name, building area total, lotsizedimensions, and Assocication fee. I am considering removing the mainlevel bedrooms feild but I want to do some testing to see if it would work out in the model.

In [468]:
rdf = rdf[[
       'ClosePrice','Latitude',
       'Longitude', 'PropertyType', 'LivingArea','CloseDate',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName','ListingContractDate' , 'ListAgentFullName', 'CountyOrParish',
       'AttachedGarageYN', 'ParkingTotal', 'PropertySubType',
       'LotSizeAcres', 'YearBuilt',
       'BathroomsTotalInteger', 'City', 'BedroomsTotal',
       'PurchaseContractDate', 'Stories',
       'Levels', 'LotSizeArea',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode', 'LotSizeSquareFeet', 'Flooring', 'BasementYN']]

In [469]:
rdf.isna().mean() * 100

ClosePrice               0.00
Latitude                 0.00
Longitude                0.00
PropertyType             0.00
LivingArea               0.00
CloseDate                0.00
ListPrice                0.00
DaysOnMarket             0.00
ListOfficeName           0.00
ListingContractDate      0.00
ListAgentFullName        0.00
CountyOrParish           0.00
AttachedGarageYN        11.21
ParkingTotal             8.60
PropertySubType          0.00
LotSizeAcres             1.73
YearBuilt                0.08
BathroomsTotalInteger    0.03
City                     0.33
BedroomsTotal            0.00
PurchaseContractDate     0.01
Stories                 17.01
Levels                  13.87
LotSizeArea              1.67
NewConstructionYN       19.28
GarageSpaces             3.32
HighSchoolDistrict      24.81
PostalCode               0.00
LotSizeSquareFeet        1.69
Flooring                36.17
BasementYN              97.47
dtype: float64

In [470]:
rdf.dtypes

ClosePrice                      float64
Latitude                        float64
Longitude                       float64
PropertyType                     object
LivingArea                      float64
CloseDate                datetime64[ns]
ListPrice                       float64
DaysOnMarket                    float64
ListOfficeName                   object
ListingContractDate      datetime64[ns]
ListAgentFullName                object
CountyOrParish                   object
AttachedGarageYN                 object
ParkingTotal                    float64
PropertySubType                  object
LotSizeAcres                    float64
YearBuilt                       float64
BathroomsTotalInteger           float64
City                             object
BedroomsTotal                   float64
PurchaseContractDate             object
Stories                         float64
Levels                           object
LotSizeArea                     float64
NewConstructionYN                object
GarageSpaces                    float64
HighSchoolDistrict               object
PostalCode                       object
LotSizeSquareFeet               float64
Flooring                         object
BasementYN                       object
dtype: object

After these changes we can already see that the data for the model is already looking better, next we need to change the data types and then focus on handling the rest of the NA values within these feilds. Weather we are going to drop the rows that have na, or use Imputation

In [471]:
# Keep only rows where parking is 10 spaces or fewer
rdf = rdf[rdf['ParkingTotal'] <= 10]
# Fill any remaining blank parking fields with the median
rdf['ParkingTotal'] = rdf['ParkingTotal'].fillna(rdf['ParkingTotal'].median())
rdf.isna().mean() * 100

ClosePrice               0.00
Latitude                 0.00
Longitude                0.00
PropertyType             0.00
LivingArea               0.00
CloseDate                0.00
ListPrice                0.00
DaysOnMarket             0.00
ListOfficeName           0.00
ListingContractDate      0.00
ListAgentFullName        0.00
CountyOrParish           0.00
AttachedGarageYN        12.20
ParkingTotal             0.00
PropertySubType          0.00
LotSizeAcres             1.84
YearBuilt                0.09
BathroomsTotalInteger    0.03
City                     0.30
BedroomsTotal            0.00
PurchaseContractDate     0.01
Stories                 17.98
Levels                  15.08
LotSizeArea              1.78
NewConstructionYN       14.30
GarageSpaces             3.60
HighSchoolDistrict      19.96
PostalCode               0.00
LotSizeSquareFeet        1.80
Flooring                39.42
BasementYN              97.81
dtype: float64

In [472]:
rdf = rdf.dropna(subset = ['LotSizeAcres'])
rdf = rdf.dropna(subset = ['LotSizeSquareFeet'])
rdf = rdf.dropna(subset = ['YearBuilt'])
rdf = rdf.dropna(subset = ['BathroomsTotalInteger'])
rdf = rdf.dropna(subset = ['City'])
rdf = rdf.dropna(subset = ['PurchaseContractDate'])



rdf.isna().mean() * 100

ClosePrice               0.00
Latitude                 0.00
Longitude                0.00
PropertyType             0.00
LivingArea               0.00
CloseDate                0.00
ListPrice                0.00
DaysOnMarket             0.00
ListOfficeName           0.00
ListingContractDate      0.00
ListAgentFullName        0.00
CountyOrParish           0.00
AttachedGarageYN        11.74
ParkingTotal             0.00
PropertySubType          0.00
LotSizeAcres             0.00
YearBuilt                0.00
BathroomsTotalInteger    0.00
City                     0.00
BedroomsTotal            0.00
PurchaseContractDate     0.00
Stories                 17.97
Levels                  15.11
LotSizeArea              0.00
NewConstructionYN       13.41
GarageSpaces             3.62
HighSchoolDistrict      18.45
PostalCode               0.00
LotSizeSquareFeet        0.00
Flooring                38.86
BasementYN              97.80
dtype: float64

We can see for the garage spaces vs attachedgarage YN we can see that they should some what be related but the numbers do not connect. To fix this, I am going to cross refrence then and if they have a value in garage spaces, then in the attached garage YN field with return a yes

In [473]:
rdf.loc[(rdf['GarageSpaces'] > 0) & (rdf['AttachedGarageYN'].isna()), 'AttachedGarageYN'] = 1
rdf.loc[(rdf['AttachedGarageYN'] == 0) & (rdf['GarageSpaces'].isna()), 'GarageSpaces'] = 0
# do a final sweep through to fill in nas with 0 in both columns if they did not get caught.
rdf['GarageSpaces'] = rdf['GarageSpaces'].fillna(0)
rdf['AttachedGarageYN'] = rdf['AttachedGarageYN'].fillna(0)
rdf.isna().mean() * 100

ClosePrice               0.00
Latitude                 0.00
Longitude                0.00
PropertyType             0.00
LivingArea               0.00
CloseDate                0.00
ListPrice                0.00
DaysOnMarket             0.00
ListOfficeName           0.00
ListingContractDate      0.00
ListAgentFullName        0.00
CountyOrParish           0.00
AttachedGarageYN         0.00
ParkingTotal             0.00
PropertySubType          0.00
LotSizeAcres             0.00
YearBuilt                0.00
BathroomsTotalInteger    0.00
City                     0.00
BedroomsTotal            0.00
PurchaseContractDate     0.00
Stories                 17.97
Levels                  15.11
LotSizeArea              0.00
NewConstructionYN       13.41
GarageSpaces             0.00
HighSchoolDistrict      18.45
PostalCode               0.00
LotSizeSquareFeet        0.00
Flooring                38.86
BasementYN              97.80
dtype: float64

Next move towards new contstruction

In [474]:
rdf = rdf.dropna(subset= ['NewConstructionYN'])

work on changing the YN answers to binary

In [475]:
boolean_cols = ["AttachedGarageYN", "NewConstructionYN", "BasementYN"]

for col in boolean_cols:
    rdf[col] = rdf[col].fillna(False).replace("", False).astype(int)

/tmp/ipykernel_1260/4104224867.py:4: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

/tmp/ipykernel_1260/4104224867.py:4: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [476]:

boolean_cols = ["AttachedGarageYN", "NewConstructionYN", "BasementYN"]

for col in boolean_cols:
    print(f"\n{col}:")
    print(rdf[col].value_counts(dropna=False))

AttachedGarageYN:
AttachedGarageYN
1    49047
0    16735
Name: count, dtype: int64

NewConstructionYN:
NewConstructionYN
0    63067
1     2715
Name: count, dtype: int64

BasementYN:
BasementYN
0    64322
1     1460
Name: count, dtype: int64

In [477]:
rdf['Stories'] = rdf['Stories'].fillna(rdf['Stories'].median())
levels_mode = rdf['Levels'].mode()[0]
rdf['Levels'] = rdf['Levels'].fillna(levels_mode)
# fill all the NAs in highschool with unknown, I think this field will play a huge part in determing the price
rdf['HighSchoolDistrict'] = rdf['HighSchoolDistrict'].fillna('Unknown')
#final check for no Missing values
rdf.isna().mean() * 100

ClosePrice               0.00
Latitude                 0.00
Longitude                0.00
PropertyType             0.00
LivingArea               0.00
CloseDate                0.00
ListPrice                0.00
DaysOnMarket             0.00
ListOfficeName           0.00
ListingContractDate      0.00
ListAgentFullName        0.00
CountyOrParish           0.00
AttachedGarageYN         0.00
ParkingTotal             0.00
PropertySubType          0.00
LotSizeAcres             0.00
YearBuilt                0.00
BathroomsTotalInteger    0.00
City                     0.00
BedroomsTotal            0.00
PurchaseContractDate     0.00
Stories                  0.00
Levels                   0.00
LotSizeArea              0.00
NewConstructionYN        0.00
GarageSpaces             0.00
HighSchoolDistrict       0.00
PostalCode               0.00
LotSizeSquareFeet        0.00
Flooring                37.99
BasementYN               0.00
dtype: float64

In [478]:
rdf.shape

(65782, 31)

Next we are going to make the final touches in changing the encoding of the data fields.

In [479]:
rdf['PurchaseContractDate'] = pd.to_datetime(rdf['PurchaseContractDate'], errors='coerce')
rdf.dtypes

ClosePrice                      float64
Latitude                        float64
Longitude                       float64
PropertyType                     object
LivingArea                      float64
CloseDate                datetime64[ns]
ListPrice                       float64
DaysOnMarket                    float64
ListOfficeName                   object
ListingContractDate      datetime64[ns]
ListAgentFullName                object
CountyOrParish                   object
AttachedGarageYN                  int64
ParkingTotal                    float64
PropertySubType                  object
LotSizeAcres                    float64
YearBuilt                       float64
BathroomsTotalInteger           float64
City                             object
BedroomsTotal                   float64
PurchaseContractDate     datetime64[ns]
Stories                         float64
Levels                           object
LotSizeArea                     float64
NewConstructionYN                 int64
GarageSpaces                    float64
HighSchoolDistrict               object
PostalCode                       object
LotSizeSquareFeet               float64
Flooring                         object
BasementYN                        int64
dtype: object

In [480]:

# Create a list of flooring materials, excluding missing values and SeeRemarks
materials = sorted({
    material.strip()
    for value in rdf["Flooring"].dropna()
    for material in value.split(",")
    if material.strip() and material.strip() != "SeeRemarks"
})

# Create a binary column for each flooring material
for material in materials:
    rdf["Flooring_" + material] = rdf["Flooring"].apply(
        lambda x: int(material in [m.strip() for m in x.split(",")])
        if isinstance(x, str) else 0
    )

# Track missing flooring information
rdf["Flooring_Missing"] = rdf["Flooring"].isna().astype(int)

# Track listings where flooring details are referred to elsewhere
rdf["Flooring_SeeRemarks"] = rdf["Flooring"].fillna("").apply(
    lambda x: int("SeeRemarks" in [m.strip() for m in x.split(",")])
)

# Remove the original text column after encoding
rdf = rdf.drop(columns=["Flooring"])

In [488]:
rdf.isna().mean() * 100

ClosePrice              0.00
Latitude                0.00
Longitude               0.00
PropertyType            0.00
LivingArea              0.00
CloseDate               0.00
ListPrice               0.00
DaysOnMarket            0.00
ListOfficeName          0.00
ListingContractDate     0.00
ListAgentFullName       0.00
CountyOrParish          0.00
AttachedGarageYN        0.00
ParkingTotal            0.00
PropertySubType         0.00
LotSizeAcres            0.00
YearBuilt               0.00
BathroomsTotalInteger   0.00
City                    0.00
BedroomsTotal           0.00
PurchaseContractDate    0.00
Stories                 0.00
Levels                  0.00
LotSizeArea             0.00
NewConstructionYN       0.00
GarageSpaces            0.00
HighSchoolDistrict      0.00
PostalCode              0.00
LotSizeSquareFeet       0.00
BasementYN              0.00
Flooring_Bamboo         0.00
Flooring_Brick          0.00
Flooring_Carpet         0.00
Flooring_Concrete       0.00
Flooring_Laminate       0.00
Flooring_Stone          0.00
Flooring_Tile           0.00
Flooring_Vinyl          0.00
Flooring_Wood           0.00
Flooring_Missing        0.00
Flooring_SeeRemarks     0.00
dtype: float64

Now the data has been fully cleaned!

In [486]:
rdf.head()

,ClosePrice,Latitude,Longitude,PropertyType,LivingArea,CloseDate,ListPrice,DaysOnMarket,ListOfficeName,ListingContractDate,ListAgentFullName,CountyOrParish,AttachedGarageYN,ParkingTotal,PropertySubType,LotSizeAcres,YearBuilt,BathroomsTotalInteger,City,BedroomsTotal,PurchaseContractDate,Stories,Levels,LotSizeArea,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,LotSizeSquareFeet,BasementYN,Flooring_Bamboo,Flooring_Brick,Flooring_Carpet,Flooring_Concrete,Flooring_Laminate,Flooring_Stone,Flooring_Tile,Flooring_Vinyl,Flooring_Wood,Flooring_Missing,Flooring_SeeRemarks
1,640000.00,34.24,-117.20,Residential,2070.00,2022-01-10,565000.00,13.00,Label Realty Group,2021-10-12,Joseph Guzman,San Bernardino,1,1.00,SingleFamilyResidence,0.08,2007.00,3.00,Lake Arrowhead,3.00,2021-10-26,1.00,ThreeOrMore,3397.00,0,1.00,Rim of the World,92352,3397.00,0,0,0,0,0,0,0,0,0,0,1,0
2,438000.00,34.11,-117.44,Residential,1174.00,2022-03-23,349999.00,3.00,INTERNATIONAL REAL ESTATE SVCS,2021-10-13,ELIAS AGUAYO,San Bernardino,1,2.00,SingleFamilyResidence,0.23,1960.00,2.00,Fontana,3.00,2021-10-16,1.00,One,9900.00,0,2.00,Fontana Unified,92336,9900.00,0,0,0,0,0,0,0,0,0,0,1,0
4,399990.00,39.77,-121.59,Residential,1422.00,2022-01-19,399990.00,63.00,"3Tree Realty, Inc.",2021-04-09,Allegra Gigante-Luft,Butte,1,2.00,SingleFamilyResidence,0.28,2021.00,2.00,Paradise,3.00,2021-12-21,1.00,One,12197.00,1,2.00,Paradise Unified,95969,12197.00,0,0,0,0,0,0,0,0,0,0,1,0
5,1050000.00,34.16,-118.32,Residential,1312.00,2022-03-08,1103000.00,33.00,"Ingenious Asset Group, Inc.",2021-10-13,Vineendra Jain,Los Angeles,0,2.00,SingleFamilyResidence,0.16,1946.00,2.00,Burbank,3.00,2021-11-15,1.00,One,7152.00,0,2.00,Unknown,91506,7152.00,0,0,0,1,0,0,0,0,0,0,0,0
8,275000.00,34.41,-116.95,Residential,1578.00,2022-03-29,272500.00,98.00,Dynasty Real Estate,2021-10-13,Eran Fattal,San Bernardino,0,0.00,SingleFamilyResidence,0.65,1978.00,1.00,Lucerne Valley,4.00,2022-02-18,1.00,One,28125.00,0,0.00,Unknown,92356,28125.00,0,0,0,1,0,0,0,0,1,0,0,0

In [487]:
rdf.shape

(65782, 41)

Finally add the splitting of data for the train and testing scenarios

In [482]:

def create_temporal_split(df, training_months_x):

    df = df.copy()
    df["CloseDate"] = pd.to_datetime(df["CloseDate"], errors="coerce")

    max_close_date = df["CloseDate"].max()
    test_start_date = max_close_date.to_period("M").start_time
    test_end_date = test_start_date + pd.DateOffset(months=1)

    train_start_date = test_start_date - pd.DateOffset(
        months=training_months_x
    )

    train_mask = (
        (df["CloseDate"] >= train_start_date)
        & (df["CloseDate"] < test_start_date)
    )

    test_mask = (
        (df["CloseDate"] >= test_start_date)
        & (df["CloseDate"] < test_end_date)
    )

    df_train = df[train_mask].copy()
    df_test = df[test_mask].copy()

    print(f"--- Split Summary for X = {training_months_x} Months ---")
    print(
        f"Train: {train_start_date.date()} to "
        f"{(test_start_date - pd.Timedelta(days=1)).date()} "
        f"({len(df_train)} rows)"
    )
    print(
        f"Test:  {test_start_date.date()} to "
        f"{(test_end_date - pd.Timedelta(days=1)).date()} "
        f"({len(df_test)} rows)"
    )
    print(f"Missing CloseDate rows: {df['CloseDate'].isna().sum()}\n")

    return df_train, df_test


window_options = [3, 6, 12, 24]

for X in window_options:
    train_set, test_set = create_temporal_split(
        rdf, training_months_x=X
    )

--- Split Summary for X = 3 Months ---
Train: 2023-10-01 to 2023-12-31 (24044 rows)
Test:  2024-01-01 to 2024-01-31 (7069 rows)
Missing CloseDate rows: 0

--- Split Summary for X = 6 Months ---
Train: 2023-07-01 to 2023-12-31 (47079 rows)
Test:  2024-01-01 to 2024-01-31 (7069 rows)
Missing CloseDate rows: 0

--- Split Summary for X = 12 Months ---
Train: 2023-01-01 to 2023-12-31 (54273 rows)
Test:  2024-01-01 to 2024-01-31 (7069 rows)
Missing CloseDate rows: 0

--- Split Summary for X = 24 Months ---
Train: 2022-01-01 to 2023-12-31 (58713 rows)
Test:  2024-01-01 to 2024-01-31 (7069 rows)
Missing CloseDate rows: 0

__